name: 'Check PR changes'
description: 'Check PR changed files and report if there is any change occurred on watchlist'
inputs:
  watchlist:
    description: 'List of file patterns to watch'
    default: ''
outputs:
  changelist:
    description: 'list of changed files'
  hit:
    description: 'Whether there is change occured on watchlist'
runs:
  using: 'node12'
  main: 'dist/index.js'
