name: build
on:
  push:
    paths:
      - .github/workflows/build.yml
      - client/**
  repository_dispatch:
    types: ['build:production', 'build:staging']
jobs:
  bootstrap:
    runs-on: ubuntu-latest
    outputs:
      ref: ${{steps.set-ref.outputs.ref}}
      env: ${{steps.set-ref.outputs.env}}
      needs-build: ${{steps.set-needs-build.outputs.needs-build}}
    steps:
      - run: echo "${{toJSON(github)}}"
      - id: set-ref
        run: |
          if [ "${{github.event_name}}" = 'repository_dispatch' ]; then
            if [ "${{endsWith(github.event.action, ':production')}}" = 'true' ]; then
              echo '::set-output name=ref::refs/heads/master'
              echo '::set-output name=env::production'
            else
              echo '::set-output name=ref::refs/heads/develop'
              echo '::set-output name=env::staging'
            fi
          else
            echo "::set-output name=ref::${{github.ref}}"
            echo '::set-output name=env::development'
          fi
      - id: set-needs-build
        run: |
          if [ "${{github.event_name}}" = 'repository_dispatch' ]; then
            if [ "${{startsWith(github.event.action, 'build:')}}" = 'true' ]; then
              echo '::set-output name=needs-build::true'
            else
              echo '::set-output name=needs-build::false'
            fi
          else
            if [ "${{startsWith(github.ref, 'refs/tags/v')}}" = 'true' ]; then
              echo '::set-output name=needs-build::true'
            else
              echo '::set-output name=needs-build::false'
            fi
          fi
  test:
    needs: bootstrap
    name: Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{needs.bootstrap.outputs.ref}}
      - name: Use Node.js 12.16
        uses: actions/setup-node@v1
        with:
          node-version: 12.16
      - name: Install dependencies
        run: |
          npm install
        working-directory: client
      - name: Run tests
        run: |
          npm test
        working-directory: client
  build:
    name: Build
    needs: [bootstrap, test]
    if: ${{needs.bootstrap.outputs.needs-build == 'true'}}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{needs.bootstrap.outputs.ref}}
      - name: Use Node.js 12.16
        uses: actions/setup-node@v1
        with:
          node-version: 12.16
      - name: Install dependencies
        run: |
          npm install
        working-directory: client
      - name: Build
        env:
          NODE_ENV: ${{needs.bootstrap.outputs.env}}
        run: |
          npm run build
        working-directory: client
      - name: Alert
        if: failure()
        run: |
          echo 'Failed'
